apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:nl/QEx/L3qdvciQaO0yh7GZykXi7aiCv2t1kTc5zZmk6vd/zp6mMjqjncvspSBGgnj7JeMY0pc9ASV9AcPlpygRmHZf2XIA5fSTY7YuPAjl2eBI8JfDkFH08CZq7fu5jlocX/3/Y2k1Ty1BHDRjQV5NsbG2bUGuUc49FJ3vL2i5Q4Y2i2aTIPLY/IWhy6r04EoqV1xpYU8AbEP+n+Ui5EMN1yL8gupPAOpzNhcaSHWy5ofthWJ6vp1Xl1N2mImU4vfzQYM1cMNPPxzqDx5lr/Scx95tQNw7P/Z3ZHPQzxOyi1Rkja7aPpikdArvUE1ckz8Mhd3B46jvvQx46uYogYA7aTsG8d1H+T7pxs3q9dqrVGEn0EFzUMVvwJ5HVqCdV+QYb/cevAEwNC153vDHcAJqapu6is/n/42ZlusA8qYWx1xusowhKmkg+vTxRXtY8zVnXI1FXNZjnXpz+jTzHwjFrCl/2IpqsORhYwJgcb6xdVx2dNGVnX6r9W8u8Kh8RJh3FmYOU2olLOwtDWK/H6lTbG04m94Hvk+L33xf8GPFQjAEae69LzqOO5G4g1QPesqS7tD5r0ta4xpUJVIZekceyjAbQcDjfeswHhMzhW8641Cr6h7IEpIx9ymAcS0C7d6F27nbGUgQyASlv9dhXdyGDEJ7bHaj2d4ZqRVjks9SNvm64YcRzEhfpYm95f44ijqjotzxzs+wWLX/WG80isUR/8pFA7jiEYE10RDPNhgtNm2swFn+O77uVXdtVRNNpvwxviMh1E45gpCya/zWYGurRT9Q=,iv:hrScAxa060Yk+7t2SZ3lgA0tlG+XQT1TtPke1UxwzQM=,tag:DIFEpiFXA7zG+QkQ9oBY3g==,type:str]
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bDNaaWd6VE5rN2tqNTEx
            bHpFbkc2R2c5b2dsSTI5RUJJMVBXNXVMMms4Clg3ZlZYRHM0ZnN5RVQvbHBwWGts
            V0JuTnVWcDhUWDc3Z3djUHVjSG9xcGcKLS0tIHQ1SjdYVFdtdldaM0ZPK2NqdjFt
            cDFFZ0NRclNISTR5aXdRSjZ2TkdPSEEKW5+ETjOlhTiVxlniDPvUo09Sww1CiQkK
            ZRfC/agLyH+BmSmIQnBRAPmT7VZm3/TifCLLWc9gNrFnLLIJF59OjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:34:29Z"
    mac: ENC[AES256_GCM,data:zHHWnhmCP67wqb/bDFOX/wwkInNfsc4ZBNf/OTiXUTcltwVfleti0MUP0EQvHWNMOO+lEzQQ3g0JpGcYg+7Pfj12KcEOEgOJZYMOoArBHxmq4tI98nrpZBqLMQ9cIfkqjVv9i2f9jdPw/JbOUQAzwNygJbj3Cyl1vmAqfnzOlYA=,iv:wRPWxYuqzoLJPxAWk8D9etkkXs+Ro2X1WB1Khhck/hE=,tag:dKSAHKGvwTTauq58DXXtuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
