apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:LTGwpmlpHzSM+d3IMbo6q/gP1mCQqRzfylZHVf1zezQZ0jpBdk1xkjCe0k3eLTsKo0+wUx5UfWMyWWbdMaxKhioJVzUiNh+F1QDlSJfSIRtsU1RZHeuckGle2VxoJR8U5G5UywcG9iS3dBlk1vnD4WGKMz7i8wzE+L2i9nPDItPyMYmvQIVT2l4oixz93OdjSpx8OxycAtEt9vkcLvKW8TU2Ebs9Sn8Q0t189LiX/az/IQT1fxWSzhxoH8ZZcrxNnOq51Ny8CH1xTXkXKxEvC1Nr6gD37phVeMQZE8xCAS32SMYrKL83RpHJ5Q7CJnoidNlsHxwBRj8+9kMElcU3afmInyptkt/UvnK/FT2BtPCwM4PPCmandF3XejirPQleeitb7E8Lui//KH0An+huw0MZQ5ERDZG1nKJSBoSG0UsCyxa0luis/uiAdO77+1+PcAw7dTWPJaFSb70soHXzjvwSWemw6FPMoe68Ultxm8zSl17MiVv48neQY6CW9V7mHSdmCnyZP6oGje62lHYBE9IyfeynT02SyXpITf7wNbDF8MPTqTFK/rreaSw1ZAyDC4L/usfHtkeFm5hCkyVc6peQfB/KJZJCyzEXZmYLWI4TWxCstAKSj10IzkcTSTr4YcbbOq0NoU7P7TkDC19/vzUJK5g0w9KA+/ghHjbAYOKbmEQ2TQeN7CR+jmm3yT/uk3Wvm+5siThRxkHk4jJ/ebuffUy+CvK+4CbeD74EKrpfRG9Wr8TmHkeNs6cQQOwBvlzmrLWZKRlcKCrk/d3gRKGyuC4=,iv:7tFALrZC/wMoq5ggNx8mpAfJ4EWAiRS7Mm30wXU+YGI=,tag:MlkPbjkaBsdWhYl00y9SKQ==,type:str]
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRlBnVERwV243LzRJSUt5
            Rm9XWHBQYjlsQ3Z2c2RNUmw1Y1NMZTFRcndjCm5FdW83cUFTSXJtb24xZzdxb0Zo
            VHZNYU1YN2hQT0pjZlQyVnN6S0htUWcKLS0tIEkyV0pKZkVtcGNEVnhHTGRTM21M
            eHcvTUw5aVhyOUlZVGNhK3NtSlU1djgKfqt6gPXurfDpmMOoFI7AMikHAmZ4rHtq
            ye+njyiSkVJa5/oY29M0cWyFpqLLnfM6EObnTk9gmdNLnN5I95tYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T17:23:59Z"
    mac: ENC[AES256_GCM,data:vToAnaiuhBiDUiJPjT049OxefhpGEIJiLffRcg9c0KXPIP2uXQ7oOgmTlwkg5lbfM6ji4KBqaBp12I0lg/BxV4wkxQ4zNZeQWN+hQyM1VHgqkDKsv9LDgsJG19B2HKszmEgX+sH4S5n0cDHZz+vuw67fLqQV2+LIcA7V1Fj6iXs=,iv:d6ROGfYDrYelLn5jl87PckDkkeNYEcQJvaxYc7+x6sc=,tag:Se7nEYruJx5m1hrWy4PuPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
