apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: '0777'
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4
