apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
# if all params are empty, synology CSI will choose an available location to create volume
parameters:
  protocol: "nfs"
  location: '/volume1/k3s-forgejo'
reclaimPolicy: Retain
allowVolumeExpansion: true
