apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-secret
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:hOPQQnzUpQ==,iv:L3AlFQXL7PfZA9rDREoS30tZu/HJiFoLTtOcIIraOtA=,tag:3yi/MmJO+dw9iWHOjsAMww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rzPddoYG5Q==,iv:359RKI0EbiEvBeaU3ttmCg4iqyjUZIoGYx5Nyw9yRP4=,tag:ULrGFaY8PspyGxk+qHp/Sw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MnJ10GaBe2AZ3pZrFa+FAJK0O8MGATpdKg==,iv:ZoMM9Zfped1XXkbhbjrXUzvS7dWdmr8b1H1I7faAPAk=,tag:UDom4iDIvElUdSeNTZCh3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d21ON2xuSWhLMDdEajU4
            QURLbmFGcnFRazJjd2YwZTdmeHUyTG5QRmxBCldka2hJMnNHdFpUMHJvWjhJYTE0
            aDJ3eExFdXNpcFRHbzl0Z2p1ajluQ0kKLS0tIGt4RGtuT0lsdnN6ekVhZlI0RVlW
            SjMrRUtMRGVGdDZzVmxkM0E0VEpYdHMK6GXI6FpdZrAc1eZ/qAvbEcMmHDxcFRod
            RNcxvTg5L3GHv0OjrTtJm7X/QNfayEV1YR4PqYwjv0RO6CZW0VslRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T19:41:42Z"
    mac: ENC[AES256_GCM,data:PseouNHsrWI5jdly1qEf/6wcH/1YZybzglpuoaR3PFDjnoE6UTjqqPMycxY9gJV9OdUnU42gDIITXn7NQTdk37rgkHYNy2LIxQfSx0DoUNxUy/bYhyRNriBw+B/D2vk0U0313yb9uqyn3goOr5FMerKr8GxRSd3eAXohprL8oQU=,iv:v0XIkB9ZzMwQ+DheSyhY2v4/rEcbQ5fZqE+1vzoAd8g=,tag:SRWbmMCVPweJPM5kFFtYTQ==,type:str]
    version: 3.13.1
