apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:t9ML4Dyk73Qlma1Ha/E7Z9sUmC4OnuxuCg==,iv:bqQ3ShcO2XggYrMk4UU29BIZrvaSXAqmgPPVWr8IX3A=,tag:e4inXJkmr3/Ae8HjM7ZmCg==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:5K1jX5AcfSJHmZlOjSjliyBUmwB2P5GZAg==,iv:LOG88bhatbo63BWpej2YN3nnD50pRGoCLWAR4itKfSo=,tag:dkWY5py+fnXz+4ZATxZecA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWxKVE9xS1YrOFdzM1d2
            ejdPQndXbWxwNHdVOUNXd3RwZDZDM1V0WERzCmljS05aTURZM2UxVTFvSVM0K0Vi
            Qk1tYUNUSXJFcEVoVE8wVTlWejVCZWMKLS0tIGMyQnR6WXB3S01QWU5uRFpheXZN
            bEhIb25TNjZwYkhtNzE0YWhhWEttbmMKxxRzd/xLZrHMlHUShXxyHZOx/iHHj9Cx
            Z6xpUbQmxJv/C4qm2LbdTUgQohaB2WJ4qCDnMtoMMcQcU3qwx9h7BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T19:39:57Z"
    mac: ENC[AES256_GCM,data:SWHXMK5iN042PRNzgQ50ATegYL3jVZ/kgHMp+qfQlz/cJXxTvG6BXPDhEUoIFRD6+AeGnK9WO4Tk7va1xZhemYN6F5dvQHAMn1FV0Rpz36Im3kd875CbvSEjxsLpuzjDU/2YwQm3uQAdUHmcFoDTRgFDyNujz0NwY+9xv95bPWw=,iv:8zpeKVhaB42IvYbQnfVfVcOCn0CghPy3KpZUGv6I2eI=,tag:KEcgFTnbPUOgNA3oA8aCEg==,type:str]
    version: 3.13.1
