- Infrastructure:
    - Grafana:
        href: https://grafana-pi.mobol-homelab.net
        description: Observability

    - Forgejo:
        href: https://forgejo-pi.mobol-homelab.net
        description: Git repositories

    - Excalidraw:
        href: https://excalidraw-pi.mobol-homelab.net
        description: Whiteboard
