- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "Cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- resources:
    cpu: true
    memory: true
    disk: /
