apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Y9vHScgM9ac=,iv:cP1zA8Ul4rxT2oY1rxMDUmm7gGBUYeYRVYT1TLslOnQ=,tag:2U7wokDT0kqybs5XH8hycg==,type:str]
    user: ENC[AES256_GCM,data:NJaWhTv16GQ=,iv:Spoe3IJgVHXldp28UX0PbzskSxr4criZnIf9NDI21L8=,tag:BtO6DSjS8WveYUr8RKBEwA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NmZoaGg1SmRRVXpVcXd4
            QWxETW1DRER6Y3VVUGlBZDNUak1URHdFeVJzCnR6ZnFTQmYzYW9yenYxbzRYNEsr
            QitYYnpyaG9BT3hFSngraFgzYzB3VDAKLS0tIGUyb1I2bXdFK0VRbFpMM3NiZ2ha
            NTVqK3pKcU4zMGhUc1EzeHlhR3lyM3MKXcGdFk21J4McnaTDBbBIlET8BEZPyz8e
            k11o5ByBpSADixna+CLphPGoEjFhQe8uR71NkYFpsldPLjHhUHeSCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T13:21:12Z"
    mac: ENC[AES256_GCM,data:Y7dD2UB1PmiBpvllteON4CtF7lIdQ6YinCZ4MNwg5g8+JzmNXj1XtFsWZE/AbQhsDBwul6ZWYmh9+QC4S6hrAOgPaikAXOOX5XE6H7m8+J7NSmm01h/jGK868J5agvBxctwoNS6w/75Pf30A/1wta2OolMcU9buOvYjqH7UWfL8=,iv:+PsMeQ7rDtv2C94BLsLQ0g1l+9vMm1g5rJBfNFz+PpM=,tag:WQznPfIRy0VA4YQyFBjxww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
