apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ctS8sAEzL4C8coTBk4rqcsB0oQewroNh2IsMLLJfpTN6jf08qYE8YI0e/mN6d4k9F4W20OvlG0BtBGjRgdLYdsVWxyxxr6Ac0U2eVWdkpP1wZhrDahMCt2YvtueKcAi5LDTkwEbzlXJnptBw6OZwJ9llI44iXDhhH0qhMultj+soj831s6YNd+k1nMiBQIc/uLHwd5h+a6MsGDUipFb2KgPbz07pftLRaqDZEZj11taFmdrGzW3vxOOKBE41ibR+oy1K5t8JKlZF6hkO6FQwDsKyxv+yJLW1E0ObDK8hQ/NtEfa4p1bFGXr8n0yt84svrsalda5AE7Dp6piBRJ7RijpX4Ao=,iv:40AQy/y7/JL9LpjucVbntURdtjBN7bMHOVS8AGaZ0No=,tag:4UHfB5nHWjJnJkYocQOU3g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: excalidraw-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNS8wVHNrSkp6WVA0NTNx
            NDR3bWhxR0l3SEJqVnRQdGt4RzFIOXFaSUIwCnBQTWJGZ3JkcTFGYWJYV3hXR1FS
            Rm5YYXEyTlozQ0s2SXNTYUNTb3FMOHMKLS0tIDFpOFhjeW40YlNnaThSTVNJd21C
            TkRXZ0VPMlBOdlRJbU0zcEdpQmwvejgKJhHd0TNnVBN4ehbJFtkQtofkcaebJm0H
            ozbw/VoFY9YGUOJTSa+Jk7Afo9yvLj/JfXye9qBdsoq0yOnXOqbwbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T20:36:09Z"
    mac: ENC[AES256_GCM,data:Ve2ud/32SJa1xlDIlK+GLKS1htsaqLjv23BKR2QvJb9NLWu/TlgwcRr8YJsL/oer2b1MZlHnI5S0LqLj++ldH9oWl3o/X/Q4TkOaPKc5iKiyvsdkkjUNnqeFUGL3gGnZr/15q3uz+6DbrDKbNFsBaNxREz+njXF8Mh0kK4ho5ws=,iv:VpeKkw18wbudNozCTX5IF7AJGsATWkorQU47UjbSOog=,tag:9ZrHt5hVYqlvTrQG0SnNhw==,type:str]
    version: 3.13.2
