apiVersion: v1
stringData:
  credentials.json: ENC[AES256_GCM,data:MrpsxXzIjHkSZ7XPOsMc6Po76oubn0P5zfog/lIWgtuMdGVafpDRiOqN3SFP/JmX0eDKiNkFSUidUe8EkY+xlzWTNK2sE3NENv1MWRzg0mLab1g1hw6EcBhESA9U7xtixS+ymJ29Ep0rCW5OPQfeDpTZgI+cuDO9TtHLjsSRI2KsZxyQ60ob/R8ye7YlVn8M1LvhbmMv99MZnmsUpDaFqiNMUlf6EvxnwVYNZNsU7difIgl7lQAoG7EX+oUTbsUkGcLCyuducoveW7vaQN29DhVBwqk6V5i6xkY5JyVSKtCAECwjSFWD6q6O02TBCSg4VgugB+cDsUr0r52u4BgjuHrNbFU=,iv:CmLkzLEOWG1Nr40wJOnVtCdFLpTgvKHqihjMAlAJM0s=,tag:yWgYvUoKPYFuwqLqgHV32g==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTUkxYmprelh4MXQ4TnB3
        MUpLdEk2WlBINjNodTQ2UktibVNvNnFBeWc0CmF2YVd3am5wT2MwVmxVUW5aa2Jj
        Y1d6MjNvbm1Oakx4TTQ1RW0wQmNzVzQKLS0tIGFBQStXWU9NanM0TnM4Vjg5Zzla
        RzVzNHJ5VTJqZFk1VU5sVllpVnpTL3MKbEi153XHwiGNmp4B5vkfXUmW0yrJ9RxJ
        qQePZKk63131w9OvUYrJ2xdHSnK2RN3fqTIXRANZyHLmCD/t9DyJUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T20:22:03Z"
  mac: ENC[AES256_GCM,data:RbGNuW63Wp9V5qbp+PzdG3v3jAzK93dp9GjhxQey+dbyZHXsAAe9rldscCUVvB0gH2QSlMLOg5Pla09qMSkGKVYhC8BMTtkWyJaxkas5R4CVDyLeM/aZiAWrpe1yYOSJ1IMHOdtp8fG3+IwOsGzgGo+2Tt/dn60zeENXymel6Ac=,iv:2OHVK/lK3RNLVIKfHpDCP4aZceW61LKCMJhpvczmVCw=,tag:S/3bmTSrK+adMycu9NH2jA==,type:str]
  version: 3.13.2
