apiVersion: v1
kind: Secret
metadata:
    name: ai-qdrant-backup-credentials
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lh/mHcXHPddk8xIxV35kxGvTm3CkosOG4Q==,iv:RJtAkOaPaii55CHIJIqdvSPzcpRwBDKnmcE8+BeinTE=,tag:nrM2HlQ4+bIGJJ4dvSfPkg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u1qYKuO7//28LnG3jeduwx1Pp98/li39Ses4Ap60eA==,iv:qffWyd74HwS4f9nC0hPWH3RxWBtaAPaRYWhEyvMYtkY=,tag:uYm21gHtqvx/xwWrPgD+Ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSFBFZUxtWFJsQ1NRcVZT
            VU9LdFlTVHdGNGNFSUd3dGFqQlJYY0xRbUdNClQ0eFEwWG40SFdISU8zWjI2UnRK
            VS84K1VkN1FxUXZqTXY4ZkxNZTF1cjAKLS0tIGtjc1c0cFZnR1VNL0dCMGZGMFFK
            UjNKN1ZwU1pBMnRvK1cySlVOakc5aG8KMQdNa5MMrdYB5uMPFUdXBBs800sGq2EX
            svP06iDUGXVAvQIRumqxO7skn1dDwG3eJnkobcMb6Uhq/QEBWkXgqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T17:52:48Z"
    mac: ENC[AES256_GCM,data:LJiIeWNUlwtpD0+Xmnv25rXFFpeI5PKxZ2Ab6TwRp0Wfv8hdehyzBLpJIrk+0IJ8pSNhAvXAsaAz4lQplJFgxMFE2rMsRJoyBrvbEl49hnzVFgJ4sTJw9iCwVslxpybci2+GtlDukmjZfEYoB5lUuOEjPJPCq9BLqUtgGAUO76Y=,iv:ms4m4A4RlJWecZVafpch0t0gE2qTKKr/ajPlBJ5hCgI=,tag:2aM3Ca/2E2pekKla4XpUHw==,type:str]
    version: 3.13.2
