apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ep+K/evo0Ef5kXLSDsEas7/2Jfot1v1v3emZOx0L4jRjjk6Mtlcwj9Il7jG1GsXikqaewC7ENtM2E4fasc6r9Obky1ugqO+Z7iWBc3V/AjZ58n1RJwV+5RIE73YqDT206aGwlcY2IaG1chlJj6siHISLU/qwJbMmRAzv59/kwFt9KVJ+af+jEGklHfr3gNkv9ynoLPl5i4Ridoqph86OCIAC+JBq7HLFwtpU/ALUnIDtvMHLcOoHwuEsJApqKWsiuoPUWTw+jg3i2BG9PR0BlorwF1EQfFBfRV00nWmrqvFGIpL0LyvLQwsf5P+k4xjiwS8ekKvbZQbEVl4MQorqSA2NYv8=,iv:0PFP/qhIBBZbXZjMeaYu5jsanNvi7UvPHvHm1SkIK+s=,tag:KffELqfLPpo3eKth3mootw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: excalidraw-pi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cWNKem50WVd5Y2FKU1lu
            ZVNuUllMaXpaZ05DTjAvMjRlQ2F5a1d2NWtZClY5SjdYc0RhcGpQYkhPWElCOGhJ
            N1J0Ym1xWTZGMDE0MUV1QmdWS0FJU1kKLS0tIFFIREJSQmRvWGxKWFdmdWtrQVFa
            YU1ZN2JydW5NWk13TTY1UUFBVkJ4OW8KjsIlxbyHmvueywsVqrWQCFsOv9adwtm9
            42k7lvpCwO9kVBnZTxyyyXbCGNjZlkhfDxGn1M2OSUNBH6H/Fb+M5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:59:15Z"
    mac: ENC[AES256_GCM,data:lj/SG4/tN2eCyaUZBvtJZfqhZR/VPEkmaCtMqPtFGl6CLMqIuCT5z/jPbyAdcqvluTkEi+slWBLZE0W9wm0IecaMLVkWchFbbV5wHC4phuyo62ZbFts3QFQVgw2CFENI+CS3e5Yt+nXo5aXa0ymhvP3ZaNzpGttRTtFS1XQBd40=,iv:Me+3wZ3r3wHd67B4p74kM4Dz2xt6i1hinZdht4mRhSI=,tag:Mi5g60bVx0H5J8zaoQ3EgA==,type:str]
    version: 3.13.2
