apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:SqzlD1BAS8/t0yBuu1HPxTjPGEQ4EXDhnwEiurpKNrsNubqmCWkVwIOjpdByQa24KJkyTxIPegbGICJH0ztM2etWg6PpTp/rL6huUfbm+5jDr0a5zewrV/pbwyx775c8dZaLUtODDahFkFPrWI5SRbbcVF5W8J+VVl03nYD+KoUszW7ynhTgnjj9SaRzFU4mHGOhtoaOLK3kKs1ycod0f1MkZcXJhAHZgSnmPBJc4ICj5FlXcX/NzTbeza104DxSp+bgwHcnVKOnB3FkWzJF9ABjAFnYqo4m3odSeuHZIgoHrTmv0gOZLNqsxYOoN3ErHCL0vlsjYtWB/MesNaRpryh0bSs=,iv:knUafRPcnL2AgJWL72/Pqg25KX78BFWmaMl+6/QZrvg=,tag:iPchQPxa9SLVGPi29dB4dA==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOFlYaDExRzJtTlhOeTBs
        WjEwNHdzdHZJSFFnK0V5cVZiZWtrK1lKaFhjCm1LdElhNmtFbFJ1YU9QQTA1YUhC
        YStUeitoeDJBV085SWpXUithRTd0eVUKLS0tIFB2K3JNMzB6M3VyckpXcVlQN2dH
        UlBlT1kvRWt0a1lJTFV3aDVhWTJUbDAKqZg1xZtIM8qSwOO9hw6vg1fI8zakflsu
        bSDuC6SnJboPw6UoF568EcePTtLuvzq2A4KHv87T0QLfAYqGzBjlsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-13T17:21:37Z"
  mac: ENC[AES256_GCM,data:VSPVT4OJC3kCTgLf054+4k+EMvupTngY2K6n/VO0zGjFZeG64QUo8UNI08AldwekV3+xe8ZL/GWCpI8+nzpQZNV8Rk7j0Psavkqa0/N80uik9SeZnQZudHM2t7Bf2dfyUFEbfah3FIwlnJGX6qf7cV/J0Pp4bUC/jogzUFouVtU=,iv:ArVmV55T9CTRNmBbmhXSQfc44DHqopB7yizGTMYMNp0=,tag:HFWcXm7jmqR/RpkheATtsA==,type:str]
  version: 3.13.1
