apiVersion: v1
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:X77QqLQqdg==,iv:ZDonNyA7D+W3EJR1rxJwt0xkKPfHWtpyiyWMFaEiHrg=,tag:PLBf0mbWh1zF++rHQtMsAQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:+l1mtcepHvfMlWiWU4iUcYRF8YhDtQxy8g==,iv:83IxOMLkK63JhMhgaPwV4GRuuff++9murArhDzEZeM4=,tag:02+8exLKat5z29qWm44T+g==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT3ZVdnV6S3JhTUpQSUhU
            TUZlYnQ5SG9Za0czQ21oS0lic2FpYmFwMFVnCmNwUTJvRUluUU9HVWROL0x2RFhW
            OVNSdEJ0azV0WGpBK251S3BvZGFUQ00KLS0tIHAyWHdjUmQycmZ1RDR3Q3JQeXBn
            MG5iKzQvZklucTNDTStYSUltTHFDWUUKuVuKzeLvXh/atBKgJRPhbAFX6YXY1dgY
            SKV0Ff6Dvx5W2yip1RshDXLEMKSoJzQfFXtNdPaXlw+fmKzkDqnYsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T17:33:47Z"
    mac: ENC[AES256_GCM,data:e0HtAxB0OsGd6iqc7dEXD3+5tXTb4ZLq4X2UbH23EjOqAnzsxTQBIpjWSzgQz4oJTEEl7yt0+Pn+njhDrdt/o/Cg5vLB2mHqQCyWyKxFwBScUwgwcmRsuGzUqUw8p56twAoZIFT0aNzVP2aSjhodaSinYfDMOl8aahGU72rxWi4=,iv:6wk0rQcCnjdQk8WvBCiL9DU3Y696w00c0d21wp0PxCY=,tag:inIZBstQpCxaIG4MRbWvIQ==,type:str]
    version: 3.13.1
