apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:4M2UV3gIbzZpQt3YiW5wZcWTRDBU12+Glk5Od0qLORS8IT9G4vqBdkKO36kb4RaF7G2RG2KGPhADohSfhvxp+8oG0zNJnlFQGU00COJuVlgVcf3KOVI2ucvQ3oftZFf7mRxEqIuz7QdKqa9cONVSlU8gt3c0osmpulJh9MZ7YTj8IqwQ/ZA90zCQH0nVxRmmWPJYecEtrhnQDD1KYYQoaQKVV9hfURBWr2vRtsTc0SMXBUCFFDZG01ebBvMgIbHnrpeZE/OHrKGySoGpiTdETHsRyElR2/cafHKkiTUnNFuqopR1uoVuhYjka1NXN5Hq6WaI2EVcvakR0adO9pnqdhETCoU=,iv:xi6VTbjPYsqBqKXjwCtVMpcyoZWMPHGlzCwWuET4KiY=,tag:h8yYeF2LJxDd4CC3jzt8Lg==,type:str]
kind: Secret
metadata:
  name: linkding
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1FjcFJ3M3NDN003R3pi
        VXo1QjBzMG02VTUrK0ExbXFmQy94aFZieEJnCnFtZ3ZqVVpKSUZ0aEk5enZJdTVp
        SWdDSzhsWDVUaDdEdjJYMVNaaXQxSjgKLS0tIGtCY0NTYXZXM1d4NFQ5YVZ6VS83
        Mkl5YjFpWmgwWjB4L2FNZnFDMG9hY1EKBASWuHtvQ5CaHmVM0sA7iSnVebE2SxeN
        ASDIehHCETvxY3buUZjao9HD0v2Gn4wXTiMZtS+K5lbz3b3Hy1gMiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-13T16:36:23Z"
  mac: ENC[AES256_GCM,data:ozOggO+MNm+LcdOQzkHv3u8SWMb3IiXwjth5/Lnsx3Ivjta2mcC1xxKptNqFWBF3oA15qM1QslwxneUDVd1nUkWHEp7y7nlB77K6QTAcrRzVzAC87mGlATdPWjBi0DGgBQywcqAz6vosr5FSZar8Nfx7CRxZUbwZ7ZItDIHyDw8=,iv:47rqBeUe3kcEd30xd38wi/ydAvWRKRdRIRmIMzcA4cE=,tag:Vyr3jW6QML9BJNkKs4/gZg==,type:str]
  version: 3.13.1
