apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-postgres
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  securityContext:
    fsGroup: 26

  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja

  storage:
    storageClass: synology-iscsi-storage
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  monitoring:
    enablePodMonitor: true
