apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:npISLe/VeNpB5Tasu0o1LJQ3xNVJFD+neX9sU01J0Xu8dFjM2UrIyQ==,iv:zt4/lhqTZyKKyVURgmTciK7mkit94RIoVzYYxNLELTw=,tag:8trBKOvOI9E0HM3KXhUSsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMm92U1ZlRElpSFpXbjIv
            b3lUT1lIMnRUaGk2aXdpWjhYQVVJWlUxT3lRCjFsbVkwSTBTdEQ1NWNmV29RYzJk
            N2Zzd2FaNlA4UDFuV2hFYzlwenYyVUUKLS0tIHhWaGJIem9MeVFDMCs5ZWl1VFUx
            K0E3c29JVTNha2srL2psaU5BTlpWZzAKHUpbNt1CgvlJCO0/mQpTCHv/Sq+EL2ao
            gVNQ9nQ3BdhPskwCBad2mFK4+P7OYHGx0kxhnoaQ/EpfiIphY7My5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T18:12:30Z"
    mac: ENC[AES256_GCM,data:MZHR+dBrX9G78oW7KTuQ/tPgPGnwmM6uLYZ30RR+mL29Dn2SYiUyxDdtEHQ9ZeP0q5wXOxsNVlkOJHBtx8N929UAgGvuGjQRm0EPqAOwN9CISDXYnoXvVu6Vq1N64nNRgN5DRTLQtRtdjiPIE6AWzrPjCJzn8CD9nu/WQLetPgQ=,iv:TTi9W3ZnYkqDfx3b8QdPzEXckerN7kLBxQy4KjgXMDg=,tag:a3GiOwF0M1ml/IrheQc7VA==,type:str]
    version: 3.13.2
