apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+3BUushaCXWQS9AUH8LuSRTApV6ml0nrn9AOFCTZRNEn7hqXKvR74WikfOvLOAEI8zwE2qA=,iv:VIG18SFyLQG4tpMFv/Ig2UGX2DBpgMsnlAm02A1aFFY=,tag:9qQEAQFM2De4aPrZ8vC3SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZjlaNTRGeU0rdUdGT3NM
            MVBhUTdMWnlUVERSd1JiRkFsVEdZeUZXUmhVCjEwNVh0c2lrRXpEUFRvU2dobmhi
            K2UxY2ticjZDSm1aTWZjUDMvSXdyL2cKLS0tIEtYd3gwWmJIZm84eE5jcnc5Y2ov
            VWg4dUFPbnUrRnphRGJ1emM1T1FpR3cKlSynMB6L50Uu7DDQorbkAjVh1TgHVp+K
            VMi/VIyHF+tuWdnXp9CDFhx5t1X3lNE3SFydcVTk0lD1L00epSILlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T21:14:37Z"
    mac: ENC[AES256_GCM,data:8OrrWGbewhlTSLSiJU4Axl2xwRrezDofNTnaQXk1bKissWcD/5A9o6gt7aHflEwLNQmrTz8A6n0FHYFppgFwGaAlYDyMZ5MB6jcsmHUGXovp0R9GrBGUuHCNiMMZPpqJtFqIIw9sEpkzF8spNoASg/y4hy3FGJwtFGqSZuML4UU=,iv:g9oG8NirhLTEQqm12+sh5rXgS1f0DI3DupKNsvH48dA=,tag:CVe2nqC/Hy0nrEBntdpSJQ==,type:str]
    version: 3.13.2
