apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ai-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 20Gi
    storageClass: synology-iscsi-storage
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ai-postgres-backup
