apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ai-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  securityContext:
    runAsUser: 26
    runAsGroup: 26
    fsGroup: 26
    fsGroupChangePolicy: OnRootMismatch
  storage:
    size: 20Gi
    storageClass: synology-iscsi-storage
