apiVersion: v1
kind: Secret
metadata:
    name: homepage-synology-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_SYNOLOGY_USER: ENC[AES256_GCM,data:ZIjFNNzegMA=,iv:Vnsy8MZXhOhXZlJ4NB3RNe14D/0W1qbauSlBte7reGk=,tag:aP+04Ni5Wbj2jZDIdwzidg==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:6NR/fj5obCd9mpzyeufXmdSy6YV0lGGh1PuE9g+o,iv:87KOzrkGIQCdj8F7jdgP4JKWs4jIRIvPHCTyu9QvytM=,tag:zzlY4uAVgr98rYRY2RosBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZjhiK0hWck56SUdyakpv
            MlpZcWp6emRWWitUSTh6cTA2R3dSNG03RUhnCnpqbGV5N29KK1BiV0dxOEc5UTd3
            OXpldXAwd0FLbEc2VE5PS0czd2ltZG8KLS0tIFpwMHZUbGtnUTdLajRZUlJQNDF4
            VldoWmVFcHJsWkhBVzZPMnAwV0tHZDAKJNLfG8ewXTVkpjdi8aiQt+wJAgoSY9/K
            I2BS/BsCBi/WawUMn/Un3p5FXsUDNPZ9pHTj35N697tfD7cORcFKVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T04:01:53Z"
    mac: ENC[AES256_GCM,data:REpeLmzKHRS8DQNdmIqAUjIt+4pCmwOtT7uerWSgpNd4+Eum9iT4w8ytkhI0AoN2kQZ/xUKWFEzXTgaFG4yaxtg/SGyIFgJRmFO+9x3FdN5IE8aYM/1reoesCoW/R/La1YlJd5U+HPzQsIi7Pq6Qlnx9aF5ibCptDPzRKSXLFwA=,iv:4rYx3WkmVRCuK6vaaQXXWAEGs+Kk17AjKwoSDpYszjo=,tag:Xjc27Fm1DNd7X66UThZguA==,type:str]
    version: 3.13.2
