apiVersion: v1
kind: Secret
metadata:
    name: homepage-synology-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_SYNOLOGY_USER: ENC[AES256_GCM,data:lHJxi2Gm0gm/4SawKuCUYg==,iv:1e6XPnEsHi8dtzBZxvABtIpTfASlyy31ly89xYdz3bw=,tag:Az/l+qjQJJ5cp673Q1s2vw==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:y/rLz2ispCkq4jMOpKzgoLg2c5OwaNtS4oLRNMLO,iv:3vSC+BjwaqA1duBRLxBf2c1yJjmhnx11QuPH057Nwak=,tag:EWuttNTRigcaM6RbcVVNQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVFAzTmQyNHVUOURXM0U3
            aFJnNDBIWHFPQ0NjckVBTEM3M2JyaXVpSnhRCmhNUFpObFFhOFUxbDVpanR1cHVD
            aXpjZlo3TTRvRDR6eGViUVo2anZkSDAKLS0tIG1aVGhqYWtQQm9iMjlZS1BobUc4
            S2wzZTgwdm9XQnoyNEtsMzdsamQvcVEKp7om0OS3rRIxV7MhPO0HeGv1fxmnMGiL
            23i0m9cedTgKimEp3lqaflq+WhDRY80DSUKWXEAARaoTKq1cWdYOcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T14:42:53Z"
    mac: ENC[AES256_GCM,data:kopxKDcT/jWcp2JSXZUvPaP55jqnPYmDn8Iq+2UP/yrRl95f8II70gmGx928O2NH+dvt0swuH22t10sb14sMjvDWLtthzPNGPpZrIMsWB96O6MOK0Lwt1CIhh8qZdWvm6eG3EYYQ7JAurTEYiJ43sL7Yi58cyjEas1krtv1e2Uw=,iv:OpcueepE2oNQouDmSfrRld53SB0SiRdGfWjkrJCt5BI=,tag:p4kD3ZTOZE+GexfVt28aWQ==,type:str]
    version: 3.13.2
