apiVersion: v1
kind: Secret
metadata:
    name: homepage-synology-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_SYNOLOGY_USER: ENC[AES256_GCM,data:kvMHuLXZcX8=,iv:MbfQujlKsdlm+xH0333+/P2i+qLF5GCfU8qLLcqxG8U=,tag:PTinF/QAiXQBogVnsLHIlQ==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:4B2i2vATEJZacXyDrQMfyNqw8QlgerpL2TkWhu49,iv:em0tcYDk9agr/2VLkxPAM6eFflzge19HJ2dABvjzbf8=,tag:nFAQy523ybD7M/NFu2WoAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK1BpUkZwUDY1NkgzMnpB
            S0Y4M25aK1BVTHlWRGNtNnZMcTVpbEVQZUJNCkE4TWMwZW5heElnMEV1NDJTVTBL
            NVZTbER5bWY2WTdjU2syays2TER2ZncKLS0tIHl5YmRmaG1uY09yZmNYQ2xKOGxV
            R2xMdlJvWUQyZmxwQmZzcTZIMGQ5NFUKFP6W5AM1qohNDeX2TQSn9pMsv/hVIl44
            oMnv9eV3XWdUcYUSU2+XaZoG3NXE5mb9EinaUXRpLURUSNQ4tyd8IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T20:16:57Z"
    mac: ENC[AES256_GCM,data:Y7h2HXiBWyTmxj1uIzTc7V4jg0YpWVp6XpLjOgRm111d/3z57Dq5UDE8GEcu1LmPdGYvx1JBYqJoJUQya/Xfm+B6NoQ9EE9NjPcOc9giAR+RhZvyYcdRcSQSW36jsY6LpV0W15sYscOM7U3YOIWTQBkMALhilxz+6eOu3GiSSkU=,iv:0zWyNXmiTy8Yf6X1O8OOR2023ce6AALKkpz1Ri1UvB0=,tag:1mIDTDj/krIeODUHhyKt6w==,type:str]
    version: 3.13.2
