apiVersion: v1
kind: Secret
metadata:
    name: homepage-forgejo-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_FORGEJO_TOKEN: ENC[AES256_GCM,data:/dj/MqxIBaPEsQqdtrxYkavB3Vj6EVqfhM14/dYoya464/qV906t+Q==,iv:KfpAIDSc1VXcW6ip4EpjJW8+pgcao+g7ImsO7Tfxo4E=,tag:/SrB2xdgo6dm/VJrxe5MjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaDBnUU5jdzFQQmhVVGYz
            Y1pjSUtpQnB3cmZqbHk1Y3ExM21tY1grMGlzCjRldzFJOGNBYXVPcHpHWHIvelpP
            L20rYjZ5Mi96WWg1cDFnQXBWSmdqaW8KLS0tIDBkUUFXRDZPTzV6d3JKdkI1VlNk
            R0V0UUpjczBnczR4NGpNZUhrcjdoREEKA5+i6YYUBuIxgOZEuFYtnYNXTMW22pYM
            H4h3ry84COxaSE8prKsqxRPiQWw9FoYE5PQasIOOMvs3dx4XICDaFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T20:37:05Z"
    mac: ENC[AES256_GCM,data:0iJ/10Ob76rrhqwO2W22BlRV5j30Mu0HAkRr1CIpZsg429Z8cJljqbVC6W+Z4ZT0v6WZhH8oCm5GRCnDDzbFDsQ4/eSzyrpDf0hKFPLK2cYTU6AgfVkgoaxWTxz6PSOeLJP+lDIJ1rf203Lmc0rhLP+Za65ynw3bK7KyzexmtI4=,iv:RIsyRFkW3WQyRsqYQA/zuzZ9DiLCVrdMGpm0T4TvNt0=,tag:tWdKZ1scPXvU+xpN7TiFyA==,type:str]
    version: 3.13.2
