apiVersion: v1
kind: Secret
metadata:
    name: homepage-forgejo-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_FORGEJO_TOKEN: ENC[AES256_GCM,data:x0YmF/2o/lPjGymm9BqAeUcOMhY4dwEL1V6+vg8V5yPFhicVludgxw==,iv:G+RBq5RZBVsfBYDuytLfGVV+SuHnN89t+vIsZDo8acA=,tag:Ze3gdx3OrM2NEHJBeTo3eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucEtzVHFDM05NejJjN2tU
            OUlmS2V6Q0d3YkFZMm9yb2hOYy90RUQyb1Q0CmlpM0QxYzJoRy9mVEU5bmt2T0JV
            Q2ErSXZac3RNb253cUt0TUpUYzJyTTAKLS0tIDhVRmZLTW0vRVNhV05lb21MbXJj
            eE9xZ3pJQy80Y1JjTWxQVE5SZFFsc3MKpy9l65+evk1uZD9up2WrD3Z5PChyI1VB
            fY/bCfkfHTjybo5DKwFUMbeOStVZSX2AS2UyrIwys60pY9A6Jc92gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T20:18:01Z"
    mac: ENC[AES256_GCM,data:z5rxykZ/q6dhMEu7HUUFZd7kHFC4XMyTvXAe1nt815ePF6XDK2rK2MXUTW9vnVx4MU5nm5Zw4xbL/r6PJvBHtC04nBSV8ybjJvs/8VxgaP12M1yRa9/piA6aXAzpcB1a+qppt4tvR/lfKqaGFM2rotv2Kf38xqXO5/e7Cjk5NjA=,iv:QRgliA3eLZFd5fpMvE87Azcj/b3zIIBQIeMmBSrKQf8=,tag:Mvr4FQICWyXGVbDqip5DAA==,type:str]
    version: 3.13.2
