apiVersion: v1
kind: Secret
metadata:
    name: homepage-grafana-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:Mlr+1MGQT9k=,iv:0QlmbRLZECdhp6SuxKUcwNiWMvuWgnjqIyLVNd9cMg8=,tag:I24/NLtxxn9tfk9FFwUd8g==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:3+Dfs75eZVZ4Ya/prV62SsOYDtMeaUxhKvak2P23,iv:Ci1AABhJ0HPPrwATUUPdsGtoHX+jq00+cYjG830SE0c=,tag:1/14z91DJ5wZNkzlZ1mDow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa053VHhvdEJoUGhRYVl3
            Sk9nYzRycWpkQ0ZXN2gxOExSZ0pTQnF3SnlZCm9hMnJWWlNBNE9JNjYwUkJUcCtN
            NWRGM0lQbThOblVIWFE3b3Q1bUIxRzAKLS0tIGxSRVJXUG9tcldYRTg0RzlsQmZn
            c1hZWnoweXhVaGI2dGVEU1FwNTNGT1UKbFBNWwUlQ4XJV/Hq373cJP8ydiTWE9Cu
            HMV9J8tetQST6q97kCp0pf6JKWb/Elj/fITIz710mYdnMxWZhWwyGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T14:05:17Z"
    mac: ENC[AES256_GCM,data:+TdUFZvPPyNNvlZXP0yjqdb8oIg6U0FhX/F1DxOHToG3YrGHfodPau6AVwAqnrU0ow+F5tS2fsyPG+nfqoHwT73N40HT2AbugEjlGOnRcucX5FF79DA005ij0OwD/EZL4SAvd1TXQK1zKgJkoMe3+s8Zm2MkVILhvHr3uJwDlrw=,iv:zw2V/Se5mzpR/Fj5umcz41s+3xpU+uXQISa5i1gyCUo=,tag:5iGCJBhsoAUZJrsjTj54UA==,type:str]
    version: 3.13.2
