apiVersion: v1
kind: Secret
metadata:
    name: homepage-grafana-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_GRAFANA_TOKEN: ENC[AES256_GCM,data:SDg89/qV6cc41r9JCrdEfraRMSkKPzQWSNC42hUxneaeVD1pUkWFo6gUEBvMMA==,iv:JAxHj/K0Gn9Wc7GV4vOUgJSOFmgwexxzyry3Dcs1LkM=,tag:8kZNCe3XYRyfeAWKRYxgaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SHBZS0FQd3hqb1Q1MGNu
            U0lHWkJ6YU1pK0NnTWdtWmxNUjFndFMrYVR3CjdvRUJiVzhpTHJRMk9TVDVCcnAv
            YUh2a001clBpV2FOd0JNemwvRk9mcmMKLS0tIGlITXVZeUVacWtRcXhBemV1UUVT
            MFNMNjRuUXlOMGp2R2RSRjZ3ZytXQ0EK11DiyUXrOYiehxjxmaVRpTPl3J7AxqhG
            vJGqLVy8jMYFy3ougEdHp/yDS2ij4+4t6j0PjkP0dYOcYJ/TIDqItQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T13:46:51Z"
    mac: ENC[AES256_GCM,data:rAZq2yyk0taqaxramA312z5Ra89Ca3W2OJPmBtvIk2m0+CJBwUL5839Z0ZMxf4EQxEK2Db905ywHI12unCsLRjy95aui3pJMZy7z7MA2sUPSaILEy9OqxBP9/awoF+reIK5N4qXmmzWbZ9XUqC6q0IoQrunDSCp3y1/kA9nFQ4c=,iv:UxZs4H2b4+xWbVXQjHyti5GerWCbhqObQ2Wn8NKLai4=,tag:dZ6xHARKSVBkocaZxjQvTA==,type:str]
    version: 3.13.2
