apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: forgejo-nfs
  mountOptions:
    - nfsvers=4
  nfs:
    server: 192.168.1.141
    path: /volume1/forgejo-staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: forgejo-nfs
  resources:
    requests:
      storage: 100Gi
