apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:GwZciHQ7i40NIox4JUIqfLGOo3mK9T3tIfYzRNuohy/8lN8YviO30STMN4XFnQL31YSwYTm21YpdKgFa9Sdr8rUOEWll9PbuwSd3fYrwTs2q6fX1px773zIAK650sJTcBas99LPjeb1rDvpXSOYrFsh8QZXuD/ECi/nSeRF5IBUTequIOwQ/kdMiN/s/25LbXOcYTgb8sSo0IVn1LF1mmPSaCq6Ts6D2i/i0s40hB9hcrXmm5BxmZTIRTgvB0FjrXNyCxvbL7JtrDD4i92D09Hp4JyEeJXM/+WAIqS+cUFzSG6vjIcyJNFP348lWIfKROdbRe1GHF3anvl94EA2X1ALBolM=,iv:A6RvW7uxxq6NWJuHitYz2RVMHdGIE0/Q+rYQoZ+tq6Q=,tag:Tv5N1pDDT7jVwu+Vysy2mA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: homepage-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVFI1VmhrQjRRVGVVVG8v
            dnJUOFNkZmxYbHlIeU9hUVdsNjdXWE5PREcwCkNROVdNOEt6VkgxRnE2ak50WVF4
            QkVXY1E1OEh2QUUzVFNuUllQeG9oYjgKLS0tIGdyZEs1b3lVZyt5RnA1UVRDOS96
            TUVHOVV4cWZTYTFOSUJScFQrMUFUYUEKd+ungKDAbcgb0pV6Fban0EIec/KEFzN4
            uaZGofn+jJgzps6h5gqZ0Q7Dl+JRzCr0oS8lORjE4GSaslqFEIVsyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T15:31:57Z"
    mac: ENC[AES256_GCM,data:7BKluGQlk/wMihVRxIeojXRHznGht4ydFXOaVfYlLMpKoW+guJ50dKQsscQdciyUFnrOFeO/ne0PQrnytaqt/dMmvfsgQaxhJFMVxegF0Iu4BHa92AGKo9YsyAOnVHHKwQb5uGqlLOMbU+fdd5DWOy8lYfejilQa0FYjAYJMyLI=,iv:3xL8q9p+PeAFhYZDp68lC1J5zuh5KiwQyC/3PV+lIBU=,tag:67OLm8Au+bs1tFIaznN/Jg==,type:str]
    version: 3.13.2
