apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo-staging
spec:
  template:
    spec:
      containers:
        - name: forgejo
          env:
            - name: FORGEJO__server__ROOT_URL
              value: "https://forgejo-pi.mobol-homelab.net/"
            - name: FORGEJO__server__DOMAIN
              value: "forgejo-pi.mobol-homelab.net"
