apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-staging
resources:
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - secret-db.yaml
  - secret.yaml
  - storage.yaml

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: forgejo
