apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-staging
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - secret.yaml
  - namespace.yaml
