apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:wmP9,iv:SzKxvJkKVVuoz90mIYUa1vdheMNp1H3Pfpqr+9InguI=,tag:dJL1Kh6kKQMgAhKL95Pk/w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:xdMP8a9617mOaf0uQ42qzASK2QwGtx2z8Q==,iv:FKQ1QZcuR40IeWjd0IsgsPX3IndaopYBNsZE0Eg/cpM=,tag:xbzT/ieUxN75ffLtj9dvag==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUmVOU1JORi82cVFnL1lU
            VHgraW90ZEEzWHlDYTQ2eXMrNWs0MnJQWkdVCjhCRktXRVBmZm5NY2EzWW8yd0gz
            T3JhS21qUmdGeklzbWJ5eU02YWFFa28KLS0tIFNJdXcybnpkMXUxNGh6T1IvK2NR
            RndEVlU2S2FYNFRuRTJyM2lmQjhSdncKI4sbChwOYx0bvplS+AzWlfzBJLdkHFvB
            qDXhiGr0yxB0x2Za4kJKPZ66oXKjaWAthygBA0cksRvfh3ItTERocQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:39:03Z"
    mac: ENC[AES256_GCM,data:6eOGjZw7YopgFKxwp4pIlIWBP3vb/K80iqFbO5MdALoxVPs5ca7ycqP8ZZvUnTIYjzNMOl1iuvlEPxiSJDkWlbU25iOCkE54wW4hyZXxwd2/l13to0Y/Ukn/H5vAgS4V1mj+YQI240f2S1h0Oy9buLN7GJ13qUR9g7CucVG9dzA=,iv:im2plMUgjKSGXHkJHy7e6LNhj69wJEu+SmT1lEYwGxk=,tag:SeZmS37ptdwECyxlaRRfPg==,type:str]
    version: 3.13.1
