apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lNxt,iv:P6cpnC6fGOmNeoWamD4zr4ndApJO/2NSmQV6Yz2ToaE=,tag:eIosqfB+/UXkGOmz6ZNQPA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:C00MlTQJMwBJrLgjlzAQuYqAmZmt91e6Wg==,iv:DipcarjajUxIGd/2NyTd59FBiNu/7MFNFKmBOyom9xU=,tag:HDHrsFLmLTImE0/FuL/sSg==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QUhROTVnZUpCY3ZyUXU4
            Y2RSVDhzbFBIQzR5bE5MbkRSYlNkcW5NT1hvClU0VldjRmJxejNlV2pHcGtndzE5
            ZStNR2F5VERRamZhWkdaSFhNa3Vna2MKLS0tIEcxQXdBS1JvTU56S1lhWW9oSTlK
            NW1uNC92Q0tJcDhTeDgzQ01CMjJMSG8KAGOE1fNfhkm+i5Hnjr/Wb+ddGBPjFsoj
            FNJS2wR27wN8dCI9DguHheLHAxmllwx7PHVJj4GvYURnpEUeVxaxBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:44:02Z"
    mac: ENC[AES256_GCM,data:rZbMkOv8n6OLDy76PkSTJ8umQpfyeKYaJzVHTfU9QyIk3Tfu5MroMGIJZAONHnyfDKeRfb3a08d1pdXPK0oOjNQGjoFnSSr6j8GZBSD4YRXcc1tvRH3GAJTcEpx7s5g86I4eYixaDTpwqPpsXpUkgpLnxGdr75kSjTYE78E9aQQ=,iv:zDNN2r3+GkNJ3ZkyCVxNyxOlV6rSmJ8QxMtfrcoHPC0=,tag:dWkGu0fBUz+hYL4PjZ9rMw==,type:str]
    version: 3.13.1
