apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4l+d+vwjxuw=,iv:WMdTWZvxqyc7KE2upZpaNoJvusnTQMacGMneSnH7XAQ=,tag:FbEcl/3sfe76Jm/Wf0MRSA==,type:str]
    user: ENC[AES256_GCM,data:TDTWw1kFLjE=,iv:Gl/z2ckeR8dFc8fnyY+D8VE0/6TGfXvzLaLlScNj4cw=,tag:Gd/YOlVV/tgdSzVsPs2Nbw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y3kyY2xVREJQS0Z6OGtn
            WUg0TmtjdG9HT0wyWXptM0prYjBnZlBhd0dVCmFrM1JQOVdWNG9wTFkwQTFrU0hV
            Q1BPN1dVSVZQMEpMTG5zWlVPbEh0N0kKLS0tIC9ueXB6STNHdkNCdTZkSzdLTWh4
            TTJHSWtkbGdRUDV4K2VUdTlUSVlsTlkKWHYUj1REzGShzq5EVq2cqc3vX/ycQstV
            uTa/13ObdhGlMTyJux6kOxpuXRmsymKIBpR+dHDrXEm4+ybEyQEgGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:51:08Z"
    mac: ENC[AES256_GCM,data:ZNFWnp6UkBsL220gKnKLSyxEknRH8dJCExKY4tqYFheTTVaABMGbh9X+1NM4v/OOSFDxkCeJ6j0j4NgAuVam2DdMDg3+myc50SE7yrRCcPDf7chka029Jr1mK9INM3X1SMGWg6RGPdSlWyI8/B6cukF82farroFd7ZPtjEiDLcs=,iv:2kDnTdtMuze0rCsV62BXU/ANWXbQiEc1IZWDIozUkWY=,tag:Rb/AYm0iJRGeXO9+CVuvnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
