apiVersion: v1
kind: Secret
metadata:
    name: ai-qdrant-backup-credentials
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0EB1LFvBBOUle2tSXeK8Pz5Qe6BzBYY3Dg==,iv:du7dG8Bdtw1psGsd67cOKPxG7dMmjXAlJ0waVn0n7P8=,tag:UEieW/Yb09X5iuaQMoW3EA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3gB0s2QRvR+DdDIX2O6z6TXnZDGisdhgkf1eTeqDrw==,iv:sdxcbTUTrCLN+kFTtXC2ppylfKQ1cZEEpDcVNbsDeH4=,tag:PR+FEM/xh694Hv+2lcfJCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcGpEaHBsTmFpTVFTSS9v
            dW5RNm5JU1FBT2c5aDhNNGdpOHB3RTJPV3l3CjJxRDF6dFJLb08vNnhwRm9QdVhJ
            VGRSVG9VRzNlVi9YeFlpaGhFcGxEWlUKLS0tIE9KVCt2c2x4Mlc3bnhHejBRcHpn
            dE5IRHh1SEpZY1BjeS96d0tjVHVRQU0KrtEoH/rgtZenLrtw4P/PfQ95XS7ygG2n
            OOlne8DaVo5q8D0pjI+aC/QbpVWPXoejcOFznOiykSD2/SKz74Ezow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T18:34:34Z"
    mac: ENC[AES256_GCM,data:ZNhyL03wRZxF1/xbYxkDIvt523KBnIELcCZ4rprL3pXPsnF6Ad7PZS+dqa4/nVW6yNmXqd3ZcbfDec9bLvkoCplra+cy7AqVhzsVKnlbC0xMOZgEuTS9bcH42UQcMg9h2S1G/Sma09fiD6hm2od3viVOmC03iUHBmAi7PzxFITs=,iv:jp73mGjSEqmFfNcu4QJH7va4dmnEeqVkEeD5/s7qUhI=,tag:qcYovYEK3QwfxZutwBCdWg==,type:str]
    version: 3.13.2
