apiVersion: v1
kind: Secret
metadata:
    name: ai-postgres-backup-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:O/UGwAqEPR8G+QpCNwl33jB9vsIe5jrbwA==,iv:ZzZD8vT6TpNPvpEYO6KNIFqw9PN9/Koejw3I41bdDm0=,tag:ofN92pjG1qs5TLpslH1UoA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:N1OD/lV77kT9wGodbw8qXjN3LIxpzHU0sHvq0/t68g==,iv:1I+U8Da8NUmwdY8ENrNj0fJ+afZqZWcoMw8c02GoZx4=,tag:If1knaWDr0AGZDTgP49LNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRGx2ZEZWdFErblJCMmQx
            MmNoTFJ4ZW9pSFdoUmZxQi9SUXFGOFRmaVFJCjd6bDJPOHdMLzdWQU9mNldEdlQ5
            SlRIdk93QUVYVzRwWnIydkd3NXBWRFEKLS0tIHQwUVdwcTNKMjI0Sk5qZTQxYlFa
            NXhHTDMwMVBPVjlKd2M4QVBzRy9la0kKx0toGExAcwBOnWRqOzCnZNBMhyzjJvS5
            5e0wfWWp/ZOtds8Vabaqd4cVgeRzETTyHhusqwRtivy5io2sgomzIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T16:24:25Z"
    mac: ENC[AES256_GCM,data:/Wk7BhRDLX1GsaBC/5SMGeMQzKXg2yGPDIkvxaEvgz49oZQ7Ab3R4AVdU/SxtKtw3xtOGYgctWK5QgvakYhIFejjChugJ+R4QFj3ef8V6FhbregyrYuZgkZ3bB/uVp3bDIe50VeCxhvnRcJgYRgQpoEwLqIvfZ0v3Q5CACxoXDc=,iv:29TXPKyBlyW3D4sekvDCf5gDvU4FKl9nPV/8ie9+aNI=,tag:7hA8xm4Mr2BYfN4sQ1N7Ug==,type:str]
    version: 3.13.2
