apiVersion: v1
kind: Secret
metadata:
    name: ai-postgres-backup-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:XzgatQrxHfmK/IZJlKnF+nC89SPhAwrvQg==,iv:xRM07HtzqVQd2iy1bHs/Vuh5Uzzbp7XRm9SFLFLMLWo=,tag:2Qt/TklVeBg56R/BFoyHaw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:kOEy5dJJ4VY1aSk/gp706QUxCGIvFrdxM2QIOkp19g==,iv:c9lel6QUm6Laz/c6QsrkHHDLzxgAYFHkHD1uIryXe2M=,tag:3u1tp6gtXTGuKE/E4AJr8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFlRK29mTjBGd3BaQ0d6
            RlkrUnBhUDlVNmxBV3QyRFF5RjN6dkUzKzBJClYzVFVGV3Z2eFBmZzNGM2FsMlkx
            NGFlaHF1Z1JsckdMTTVrMmZUQWNkUGMKLS0tICthWWV4M2ZBaHh1NW9CTE5WRXo3
            b2xDZWcvQjVyQVJKd1NLR3JUTEFPOU0KIN+yK07AWLUgeIsBL+HiE3RowXzrBQkj
            fSxO1JKEa2jzk2v4BPhoBdk8+phTOr300pIuTUo6MYbM1gYVVv5cxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T20:44:26Z"
    mac: ENC[AES256_GCM,data:HH/EfjoybBVtJzQAZbT9Ehd5+Yn5jeUU2S65kL7pQAP/xMQgqvhmlCaiY/hXW+X/HfyEKSl7iUiItYWGEr6l1w7swvdog2j0X99NeXuRmWjpFcaHYdLjtZRZvUBA9oVt8sdTSEitIP1n/BqzExSWpKxiqCCQzLyg5zIbBHurLA8=,iv:zm/N5oKAP4HSOZnnNQnd4MDganlynCyNzqxabx6/mz4=,tag:c+eJL2aIFqABkvm5S+jNvQ==,type:str]
    version: 3.13.2
