apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:he6U8xaepgteIo4StJIkyzcpb9Tf2D3+JeXrosOKpB9rCRmYEGFlZEVygwC781qi7IhT5DCwHTreq5qerrEJRfwOxXZEFV/p2kd3nvtgTTwipD/UZO4wAvGqyE+4HTGkTTnoaB2AHxyIBSHMeSQfTymobJhnfxdbUE3kGWPNdcny+v7A7doY8LxId6NcTy8yWreNkPFRTcNwTgRqfKO8CvnlzBlcWb98I+FdN59HZdjvRB0sicTZ/Ma53S8PCp5twFdqtKPUjslLzd7G8p1NZy/+e4JQUt1HFjZP4MkRu4NX2l7r+cf8zovuuFo=,iv:PyKjHTXCFm3joLl9drAYT4ls3uYpofbZj+OkDrsIy/k=,tag:CQ7ECpk5jOgfSsiSOXaGaQ==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
sops:
  age:
    - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTlhkQXRIeGFBU2pFWFJC
        VW01WE9iQXg4aU9LbE84OC9xWGZRODRycFdzCk41MGdWNlNsQ3psZFMyT0Fka0s0
        MDZDVGdMTXhMeDIwOXdIOTcyS3luS1UKLS0tIDFoL0Nza3RSZzdQY2dUZ3VJVUJ3
        NHU1ZVFIL1EyeUtwZnFtLzVwOHpyaFEKbC3/6r2S9126FoTl37JqWTejRU7uOrFo
        CYlFTzNCcaL7TAoyQcVpaDGXlUcM+twcUCDiJZQcPrRWaklnHHBBqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-23T19:46:54Z"
  mac: ENC[AES256_GCM,data:qZ8HQBuPdpKL1A0aB40VtmxE3ubnAlaaetZ6HZRwXyINx+DbB1X8fOo/nAw3qFyT3zv3w3fogrZs1256coGKIQ1m7ddF90h8qP9sme4CL1C9Lc1emB2O45hRd+y3ompeqPVAjh0oDwbUCfkp5qNF6thOq3K1IrhppjeGLDdFTCk=,iv:wXAA6eAKGUVOV1HWxVfSuuQkSgioJeH6/DPl5Q9mQIQ=,tag:m0I8L01yLT/U5uxBI7ECMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
