apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: forgejo
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:1.36
      command: ["sh", "-c", "id && echo ok > /data/test-k8s.txt && ls -la /data && sleep 30"]
      volumeMounts:
        - name: forgejo-data
          mountPath: /data
  volumes:
    - name: forgejo-data
      persistentVolumeClaim:
        claimName: forgejo-data
