apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-secret
    namespace: forgejo
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:ezCUkJyi/g==,iv:UgNoYnQOqdiSzl8VLam8qpEYNN9nb81SM4OCxZs0iE0=,tag:2G1rmQX0mpKi7/VugEjzvA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:QCb1qDHLtA==,iv:2kaO1xxx+vpyE3m/Swigzw27wLOJGj6Hocjvhdov2vg=,tag:6J2ZBGgRzlxI7uhbmRwJ9A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:SkvcEs9nVE+NCVQKWmtqdT+aeG1rJPX3ug==,iv:px1qXE5QeYsKPPVWHd1lodheA1zqX7uDGYxYf8cdJIM=,tag:d17FfW9M7XCmN5ujJpBBDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeHpMRnp0UzAzUmI3UU5S
            NDVUSTRob3d0TGlvbGo0MWcwSjFWelBBMDE0CjlwYkpaSXAvdUw5N2hySVhlU0o3
            Z25BTEVNMEprNS9vdUkwd2tNTVFaNVUKLS0tIEZ4eDNLakhvYjNZSXF2NkdQT0E3
            aU9ZMkwwWWFROUluekJpRXZ6eExFL00K1Kqa5DvSeQR8RdtWtlR7yMNCq4vxFP7B
            /OBlnbyNiLKt3OB0j4wxrwqD5qPhF3dluL4bPrtklGcnIUPv264T2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:12:46Z"
    mac: ENC[AES256_GCM,data:1ni7WsN7ToRlCvS8yE2kqTONUA45K6rqf2m1ae7G0nSDxJveqtnpIHtSukufyu76OoNmOExhbXa6/hdmS9IQ02MTwyDxOserujVrmX3Fvl5X1GJ2WzIdRxSAGXJ/dq7PyhYy8NeSaqrw99CRWFwIr7p8ydDFp7jrghWEbc+VKVY=,iv:zT7kpVrh9gj/rwMhG599DfO9pvHCLlSmWT+4sODSv4Y=,tag:zzq0FJ+mYFdiCNIGQ5NQAg==,type:str]
    version: 3.13.1
