apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: forgejo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:pARSax4o/ykJYhtMgpxwTSNeSvZdCQ2QNQ==,iv:247OiM3oiYpTpQUs+PTOAEXJ3x4onnztnCDPevoqZJU=,tag:DV4x1HlEnDtUTclmQLzgLw==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:HLgt5pSLLfM3fF7a+r6B6LrkmqlKww4LiQ==,iv:cCQtT2Bff8mnOByuYArQNKzEhR0DTDgGCF16cGEjNJs=,tag:dh6zXyWXcExw9Npj2++gLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS3lsdXNOZ011eUpnRlJD
            cHlOZUo1dUx6S1QxSDlsZmswMG5nRk4ydWlzCnB1dWFlNHBEWThVd1VjN1pHMUtC
            ZjROcVJYWFA4ZHI5WXp0dzZ5QS9oazQKLS0tIENuVmR4dlppSEJlM2JpakM1RzZk
            ZmpmcERrZU56bnl2enNwOVFid2Z6MXMKqLO+P986NPUY9P64oqWd/fVsnybTngZg
            nsJotoMLMmMXazVV3MuiGyJtjX3P6v+CTw/AtZ2ocuViK9jUavdekw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:12:43Z"
    mac: ENC[AES256_GCM,data:/S5lKh0BwCNA5DuT3cvLAqNRIrhac2Y1Bi4eOpkjGxD+0px2xzV13eWn8YJQfjhzVdf7WjWuobcKhBU8idAqsCvSDG2fQ0KNX523ZuW60zUlT5ArQnWmMlZqd7E0urnlGyhr+ev6c5UQgwUljU+cREb56wKTAe8l7ejtE9n3r0c=,iv:g2vUlT0Wo6F2vCSyzSi4rg+MDe9Q66Q0+NnOYeGDBIQ=,tag:wirSU0v5k0Z3D6eHS4N/4Q==,type:str]
    version: 3.13.1
