apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: forgejo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:tKxlE9fLi6w7,iv:w8aKdN/Ey1bKtE8928Q+B6Lw8RkhKPVcfqbMOFjqbX4=,tag:1YJXkGoYe1qkYz3wb457KA==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:+6dERyfNGPux,iv:w5pbPki0Fqu276p1PrAh68++R+JQI/9F9FL3yu5cRho=,tag:o811ydckh3Yg0xSnK1MHyA==,type:str]
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbWZ2UWxQa1ROajFyOHFO
            ZmxzdzBmVS9aMTI5ZlFidXk1MTYybnE4MW5zClRoS2U0bVNYT2RqcElCMTJrYnpY
            YTZ2am9BRFMvZGczZDBTaVZENzJWV2sKLS0tIEdlZUl6aFNXYk1oaWFnQlBLdDls
            REt0dXNVaDNzaStEdk1GZXUvOWVzcEUKuI+4YhhmcpD6W5vPs02drnE9vSBBEd+O
            qY7xN0nai7eV8+R6h6eBtdKabIb3Jz+0zw8ph+85lhtwCkehRl3O5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T19:26:48Z"
    mac: ENC[AES256_GCM,data:SqxM8InDag6zVr6CPOSVNQ4vfUpzK4sYe9iM0Kd6zh6bRpZoy/tkvApIT3/1EYEK+WbCyqD8pj4EPIzyeXj4YxkayhrWmbY4SkZ6DALDivf4z498zgp8ZdhdKRQIWNWl344qnOm3pPPfnonFZV+sWvSr8vQbP9Qsq3qIWfMVFrw=,iv:GuBpkOZTW/v6haZ+t83cMn/ZjFqppko89+ojszDPuTw=,tag:vGW3i90p2b3t08TlztxrSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
