apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      initContainers:
        - name: init-config
          image: busybox:1.37
          command:
            - sh
            - -c
            - cp -r /config-src/. /config-dst/
          volumeMounts:
            - name: config
              mountPath: /config-src
              readOnly: true
            - name: config-dir
              mountPath: /config-dst

      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest

          ports:
            - name: http
              containerPort: 3000

          envFrom:
            - secretRef:
                name: homepage-forgejo-secret
            - secretRef:
                name: homepage-grafana-secret

          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage-pi.mobol-homelab.net"
            - name: LOG_TARGETS
              value: "stdout"
            # - name: LOG_LEVEL
            #   value: debug

          volumeMounts:
            - name: config-dir
              mountPath: /app/config

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

          readinessProbe:
            httpGet:
              path: /
              port: http
              # force the host header to localhost:3000 which is always allowed
              httpHeaders:
                - name: Host
                  value: localhost:3000

          livenessProbe:
            httpGet:
              path: /
              port: http
              # force the host header to localhost:3000 which is always allowed
              httpHeaders:
                - name: Host
                  value: localhost:3000

      volumes:
        - name: config
          configMap:
            name: homepage-config
        - name: config-dir
          emptyDir: {}
