apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-secret
    namespace: forgejo
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:ME2mRJVXCw==,iv:vDoE8ieYugCrYd2SNA8AdD7UQe30+Wdj8heoPV35sKU=,tag:3AF4HrDfXC6RKbLa3BBumg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:s1SKc0KioQ==,iv:nGk9tnM+XSva5o4UWYzWBuR65hPYb1beEb+7MXI8XHI=,tag:n+y239kGjUC3SQeKBCYULg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DiLSOI6zlNnD7kfdjxGWkmc=,iv:i/UHPQkZuW6s/N2tK6/auxZdHD6zlK4in+tKruZ9rEM=,tag:sZa5Ad32uR7tKKUjUacNNw==,type:str]
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZCt1K3dHVVBwMGVXSXlZ
            cGVwWmtwcnFvZVQyYmFMTnQxak03eUpyTXl3CjFCSGNtZWtsOGIyYW42ekdDVDF1
            WTk2OFg1Zm1KK0ZhZHlhL1V1WC9xM1kKLS0tIFBERzlIL1AwQmNRWnBxcWNkZUdZ
            RkZjRS81UG13MGQraG96SmpkOFFIZ0kKiRm8zOhq2v30yrDBwC8jwLkhuCUBRfGr
            43wlU4IktB5wq9chuCPE5otXpXIJhSrx1zYDBfLRvEc3ZOz9AofHsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T20:24:06Z"
    mac: ENC[AES256_GCM,data:bmKOUfO+DZ8Fcb8xONCMfqJ5j0gjAcOxngu54gej7mxW/jn5QZ3F0aVUh4DCf/PgYmsBMnl5myVDqWz5X2ccKeaNmDfJIFOu7mOgKq5DdkTx82I/yE7UW1QMmfBxBqQw5Ks+i0fi+tF6ObgZnWaBYJx0w8Mc4Y9YVcUt2t4AZ70=,iv:mDuakX+qKxaSdUNTMmrEG3ypgbVVMzsZ/OT64A05n4c=,tag:gX2pDnTXTxH/6nsURplDeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
