apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-staging-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vikunja-nfs
  mountOptions:
    - nfsvers=4
  nfs:
    server: 192.168.1.141
    path: /volume1/data/k3s/vikunja/staging
