#!/bin/bash

/usr/local/bin/mise trust /workspaces/pi-cluster/mise.toml && /usr/local/bin/mise install

# copy age key in mise standard location so sops can find it
mkdir -p ~/.config/mise
cp -v /workspaces/pi-cluster/age-devcontainer.txt ~/.config/mise/age.txt
