apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret-backup
  namespace: forgejo-staging
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:KKClP5t1SNxaOk2afTQBvy58lEyVXCIcJA==,iv:BKKv5mVeumHkBJhwTIPzBwZsMsIdYCrm9d4+l5Nl1M8=,tag:5YkTOWcZQ2p2ZG3d6Pi0zA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:MUEw64nm7wzQcOYET9vjYRVm1V3wENsJsb3pY22+sA==,iv:PNd4m6e6ItKQJf4LIDAsTit86zKxiDlnscI8dVesykE=,tag:c+uogP7+M7B8xb8rXU14Dw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLzQ0TERoeXFkVWlVRkVQ
        TWluZ0FoNmpPT3ZaTDhtY09yVWhrSlQzaWgwCmdDVVQralY1M1ZKV0Jhdk9EZXBJ
        THhNcDJnb25IMWV2cGF4aTFnTXBoTVUKLS0tIFF4SlNsUTJXNE5QR3p6Zms3MkZl
        cVNOUVoreS91RnV6czhaUU0zQlRMU2cKsG03iBs1pmiMxG2hMc4+Q1KqZrDF54fA
        wlaNFk8CoINQkWXFm3XCbcH2sgOg/kehS8dx7OARkYTymrPTaI8+TQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T20:25:01Z"
  mac: ENC[AES256_GCM,data:3G1oQS0ThOlrsxJaoDRoXNP8Hs3uKrsb4xlC93vsrIx3utWGoF1coFpXf0sjiYiajtb6NC3HtUp5hyTLcmBICSUgdC0kTWtq2pRhkXkr+8J3kUVyU/znA6b/gM/symCcFJvGXGwT26Akuw8d8bOK8XDKwJbkuEes22u0IvNEmRI=,iv:plI93H4Io2ub6k0K2Kr6vJZ03QskkZLOfSz7VAbu01Y=,tag:R3INZZdJJlfIqMMaKCxxXw==,type:str]
  version: 3.13.1
