apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:aRkV3c2sLNHMPGLHZ9AHfDx8UuqSZz02co6xu/YoVxNexbBvpT0JwA==,iv:j//zrj04GlN4anBN3/wK1y+qL4qHaZBM0GE8gi9fnjc=,tag:1ip05pFyVD0CAvVntm9K1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2xOYWNqOFIvQWJWUTNO
            dWJtOFQxVzlVUzFCMTlUQktGNVhLdmRjR21ZCjk1TW5PcGhjc2VmVU9icE82a3hn
            ZFp3UFF5aFpYYWdkcU90ZU5OMXJMd1EKLS0tIEh6aDUrdFFad3JwYnlyNU1HZFlz
            ekZIYTNCcnNXYTFoYU50YVFjelh2SDAKCBZpJOhuw62mjQlqgyiZhtpqA0VuU+N9
            iFxSHAPqLZOzGsfh9a31JuXR3BV0rzOHPz4FLejYHQo2Kr/nT6PtMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:12:53Z"
    mac: ENC[AES256_GCM,data:K7n++cAMSK9UH4jVmeKejS0Y9F4O4BN2YEgOhOCgMsNhXvcxn7rzrYc7jvvdZYWwI2yRHuokCk8SUGZDLGfGRMaHKofEdcU39H9H4N+h/t9FUtnzBy+3/y2vqLW82WOo9TJYIjQSfqJ7ceHaSgDsEICNapwoL+h9lCPlGxitYL0=,iv:zPVhLvI1npbTG9eWDfaL+9Byn6MIl2wMO1lUmthivnk=,tag:yfhx+HvMhBDp4zN93rilbQ==,type:str]
    version: 3.13.2
