apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:wwSXxf9EcW5TPWn2FTNFl3H+05Ojul6GKdFPeHQ0pajkgjMmkCRAWw==,iv:/sEEAQFRFQFmYa4K7wu50zAUY32s9sb2TsdwN1b8M1Y=,tag:MNTlpk8MkDKNL9JC7nu7AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMVgwblZyYkp4azZEcGdY
            WjdRTzRBUVhqbG11dE1laHRkNmRtRjQwVUNnClROZVpkRnhMUHAzdjRFZ0wyN1o3
            eE00dXFydnVMR3FtZmEzUHZTbE8weDgKLS0tIFJzVFlHcjc2cnJNaGNqU2xhOUtJ
            akxDRm1NRk50Sjd3ZVZlSit4dGNoVGcKKT3k9zf1vMAIhPxeyZVluFd5wsaodPzh
            dGAFnNDwIvXQHF3uq+D/PUqlOo2q3BB3UeiHRiIgljY9Q4AuFeWQvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:52:13Z"
    mac: ENC[AES256_GCM,data:4k0R+/1jLmEMtH82l95tzwJ15BRrhkrTF6gQjVg/Mohh3N0TcuTr3Q59wFkbwGbdt7VOz1GJJ6/+4N9SiOjJan+o5M2wnmKofAbVnzfAfShxVtkTkDNwq6QHiGUf9c5Wzcw2M/n59ttCQecPw/9QGnD5SplG/RB8tfQGE2q688k=,iv:0A/HEQgKjmn5kZK02HabT/tgbbJsttXrqfZyITEhKxM=,tag:xwXC4ReyytXxaPPYrrpA0w==,type:str]
    version: 3.13.2
