apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:uVwHQ0+izsG3FYGyKWN2DWgWgPu7Z3iwCjGozzAU,iv:K6C2xg80nY6iaqkTtPvwr/dT8oWtB7pdo4Jtc/xJVIU=,tag:EQH2jM3ka2TNgu16nha36w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cnBabmxrZ2prbWRzNE9R
            NndaajZPVEUwdmdhUHphOVZ4QTgvNjRWcmxzCm93UmZVZm1Zc3JpYWZaVklrU2ti
            dlhVUEcrNGs5Q1FXSzF2MWhDYk5qVmMKLS0tIEd3NHRwNFZDUHArVlduSjQ4Qk4y
            dUluUm9qdm1nczZuNGhsaXI3dy9nSUEKs0iyEsMiSL4JLVCkf+ycTZyOpofga83n
            pPCHNpLTCSwLK86LX+bJ6on1wZO3rxUu0BARooMX4BGX+Hu+RJ5iFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T16:08:41Z"
    mac: ENC[AES256_GCM,data:KihDNjR2O7eAQUSSJoFPokFBEAOpXPg1j+PXF1+NES6+y+aMzwrGczQ1yfxDa6AAVC02xXADY0XFT4RoBqR9zkzcc8nwJaarOu6AHLiHrme/A/k+XW+1EaJm/NR81XuZi5g2e5EafqhpSgyR4cWZs+ol5Z8a4doihtWoLj3vdGY=,iv:zwqs5eq8yqQx3mqdDxGJeHJvi7G+moVG+1/NjUYy+Hk=,tag:+QkPo2SWsz7q2HHUxVpSYg==,type:str]
    version: 3.13.2
