apiVersion: v1
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:6kIouf4XkQ==,iv:kwOWPjhdShJlAqd10uWS9ifm7a+Ceq6Zh3xRWsRcbZ0=,tag:9Ph0Ord1fqwLgcN7HR9lJw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:t3W6NICUcTweO1/jSq+8kY1YML7gvr6kYA==,iv:SVkpoGWT3s6WL4FhG18YtoaIPRoNmRdkfMQqMUWyKOU=,tag:GOvOFB22Xjv+HcoIr2U8lA==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUlA5SFFoVlNMWXMra3Vx
            SjRsRmt2TkVUcFB2WTRxNjBEVXV2UzNYOFhvCkh4a2wwZU5BbkhmMUdpMWFmd1ky
            T29XbzhhMEdQQVYxUG5oeHFuOGxRdE0KLS0tIFkyQTNtT2l1SDZPcjJ1SldCZ2dU
            WVVQK21XdWtNV3NURDFMNlVQRlBDWmcKS9I7hIXE8TunWXg/5IAHP1rC/14HzpXy
            g2lkAltvtdMPg2wN/rubxEI0F9ySncrqjlGdpMhKuaVSOdTR+G1fMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:51:18Z"
    mac: ENC[AES256_GCM,data:AaVvbpAoAo7TFfDs9UL43F55gV6QNKxApcuqEO+dMx5CHMBgEud3cbBsamezzZHjaoT6/y5WohHN8DiBV034PpFDzPsSUH3oO/s5sBU5DF4/unFQACnNDMGCejWzZ6WSk8pG+nuFXqFoPj3koUZzXiQ3xO6yqlJSxfvMeZnhpyY=,iv:bqY7YwBn3A7ivFG3v5fUec4O2xxR53q37ftBVRZO10k=,tag:4rWTUHafQGLEx1gsrtBhNw==,type:str]
    version: 3.13.1
