apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:HOmSIQ==,iv:Ct0K4OVF4VxCpLWwg+JoDn7S7aSX4kHdnf4XYO7NarE=,tag:yeUfiW3zS28KgO7gvqh1YQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:i6jvSUo4WmxFdul4nQdD5yT/+eGi+mxlsNzgSg==,iv:PlilRR9zeG8Y3+V+XMXJGR2goT1Xl5pqoVd7ndoFixM=,tag:SZqQf6VNODTi5iSb4eB0rw==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-credentials
sops:
    age:
        - recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVjM0aWQzeWhqVlNrVnN4
            aUdxY3YvOUlPUjlDYjc3b3hnWG5UcU9VQlFNCnd6S2E3eEx1TXliWVJELzd0S2p4
            VjhTUmI2K2NRYnR2NzIrcnpnMnVzRzAKLS0tIHR4NzhORmRPYkkyMXI4NGFidE1u
            NGhIOHBrZGMxMXRhWFhDSjg1ZnJ6cnMKNDiMU46MkkWCK4W5RLWvJD1rDqUCIrzw
            qaCRoMCUagg2luvEX5DnuASFfjiVX66PhprFSNaoTaHj1bgnYg42xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T17:55:56Z"
    mac: ENC[AES256_GCM,data:XcjnzX3RaRIi58Ie9FZ/uzEGpgEDTLWbA6No/OknvF1q+mVUMqe9ESgERL3rP6+gSskw9EpesZZnwh5RVBodqqXPj8Va04iHrpl1Rcci0qHKDm6xgdNdZffRqIiG0w09g9gfX/P3yB609QupjIAvCAIVrc8XaBTx9C4vC4nfvKI=,iv:4VfEoVbd+K0+di1UgXlQVBUO7z3IJixveKxWIoI9gu8=,tag:abS6CANwhpqhjtITF2uQLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
