apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-platform-prod
resources:
  - object-store.yaml
  - scheduled-backup.yaml
  - secret-backup.yaml
  - scheduled-backup.yaml
