apiVersion: v1
kind: Secret
metadata:
    name: ai-postgres-backup-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:bdBzoIJV4TiIxU0ejC/1QPamvp44f56O0w==,iv:vbrwCZsjeqQbVsZ2T9iDfmrA/IpWz/SDGWq7x93pIus=,tag:9KT52Qjwwm5wjRxAqiZLkg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:25jLdsEWFLi5v9D3RFy8e3vVgarhDrg1XfiQPlij/Q==,iv:/a3JrV1K10gVEmEfk/eOptebcAgS53lFDwz6mNWGPv4=,tag:Ta3xQfWoxspKtuxnIziQqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbzZUOVdRSktFWUFpb2lh
            a0laWGtnSFR5c0QrWkhQOHI5T1hGQ3hOSXdBCmdpMS91WlEyT01ZdStBaTZ4QXVD
            UDRKdFNMT050N2o1T1FWdDc3L2ZlajQKLS0tIDJKQUdHcERhSmlITnZaYkF2OStG
            RmVzdXRFdWdRWFNVdkhFeVp5dm4xZ3cKS4qfli3dQz3lzbVDQDJ4cpnl0SYGwvyZ
            XI882Ni9Tn6O1P/p4iEFN0STZ0UUceaI9wC5yPk9SUOFrUvE8B4ibA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T16:56:32Z"
    mac: ENC[AES256_GCM,data:dbBo5a7Q1gwjrzJr6pSWvCtCXdDp91p+FBngj1yJmUZd2YF2ghov5qmpuOlJ2oLy2ZWrvc79yCogo+PBqhHeK8UK0ZCJlShkN+lSC5D1M87KkmEYh22E7n8QRis2hyvRyqTEajhE5v62y54+6iXQxE8AGsXZ5HDVJRPA4DRxrj8=,iv:TWVU3EzCJJy1kr7aU+cqDXLZQFaQhrxlm+S6omlEUhc=,tag:CBoA9yW5qpx3zkX74X/MBA==,type:str]
    version: 3.13.2
