apiVersion: v1
kind: ConfigMap
metadata:
  name: planka-config
data:
  BASE_URL: "https://planka-pi.mobol-homelab.net"
  TRUST_PROXY: "true"
  DEFAULT_ADMIN_EMAIL: "admin@example.com"
  DEFAULT_ADMIN_NAME: "admin"
  DEFAULT_ADMIN_USERNAME: "admin"
