apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:eRevEQ4GsvLrl+MY4G52+2NzK+ahenEnD0fX6PMQ9ZAjy6aM/UjOkvR1OkxX2G7fuBtG7ilYdXZyHic8McBWkS+1H6Zm5h8GGwqNtYuVaVPDVTk+LG1r/qVEEAItvCAs/s8YUhfy2GwpSsFFpuURa8vftC5VBxS4p8l9wDS1MEE=,iv:lZKWmAY4VYHWfWgv6FSe1qshb0KI5MORMjvUBklTSqo=,tag:XcOLwL42TX22IMfyjBIV1Q==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:ADMEXJBNHMKv3LL5Uv0+6MIgqNglm9jDFdEN6ugi,iv:z0Zp50ZUfA+yrrTVjPO7qWO0fcW+H69KEbwiuD9Gb2w=,tag:cpLqd+5DuwiuqUsuBVYCUg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gmF6bo0S6Cic/DXgbi6BgqGgSgwGfLZh2AHqehYO,iv:+pYl2tiqeGVFKF2bPBfkDA+o2XLGiV+oETxfOxoxAPg=,tag:L494nFp5U3MnT21u2vG0lQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:QYNnhyAKErMYCl4NZmBRkM/YTA+i/PLIi+QgrBnXXEUW/hNel/qmoi8mpkGws8nju/HTOUV2VwWhGPIJe2K8gqZAmDzCt3kiiS8Ynut3,iv:449Pg6p6YM/ulStwpur9mGE5+nJDToZFtITeIgpOTNw=,tag:bQ4kLszz8dhb3DP5/Kh2xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN0ROU0Z2eWRLQnRlaVRo
            RzZzZ2d2T2Q2MVpCek5kcWFnSXNZUjdKcnhvCkphcXdNVEl6eHlQdEVSOFF6dmt2
            QkNsOHg2YjJ0ZndoMnNGMDdBdUN6UUUKLS0tIGFHU3A4dzVjY0tWVFZTR1hOaElJ
            c0IzckVOMStlaVhsdS9BN3VEV3ArVFUKKhz1xdj3nqvPAFhxBPqN+pFndi2yf2Gv
            I2sYkgi2hd82sp+3NbdnRmFXVz32KWxVrY/8nB/XFvJExX/udeoD4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T13:10:26Z"
    mac: ENC[AES256_GCM,data:gKM7L8uUMatlazJI5NPVNPqA7c9yhJHGPn3ARAuSHtsBVVXb/oTbefaAco6CmkD1+c54kmF/NA+0VqeWY58Qxnwujc7EJ4+i04eSMv/kIOGGJujrvuM6ej14QMmujk1v+Q6M2/rIhrPEnqcyCqwAehFIvkM5NQ4FF0j2reK6yFs=,iv:fxuHyle/tQhcOPDuiSKd/jB0tbK92B6hLDcZuf6Q8C4=,tag:IG7r2Vl3ZzV/uF2Zy3gpPw==,type:str]
    version: 3.13.2
