apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:eX47d1OlFZp97t0qc/XkSvru+Dk1h5+uXcDMRZR4HHuoLOQ2wZZufZEVU2oar98uFWiU8JkC40W1w4D5zS1OICwMdS7cm0vrT3W+v1/ODj29u/3Un7ghZeSnAAzWpDFSzLuMF5ifTeBrW3/0sBeuYndeS7y+vlry8S/Idh+ajxs=,iv:gG6ZTh0axU18DCz1OWS0ucaTal9dVYWqxQBXqbqwPss=,tag:B09nbDIIZ1PiSeCD8PjvKQ==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:4L1x1gqOlplJY7l9O3DO0oqKBgYmHf3mp66FrTYf,iv:ES0U0ClYec1xd6QIFRv03MgdQ3JXTo0C0X3FW6i9wA4=,tag:kdgNzTHs4I7662PgmTHzjA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ej4/qyS4YYXsr8nvpRmOXSMD7gUlDHAU64cQ6QXt,iv:ayCykOEiUBscKo4Ce1H3tLv5jNbnVWJa1lpZ0mHzwlg=,tag:WzG/4jdkZAcLH10mhZ/a/A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wjCkZajWixy+wgw6XSoFUACd5MEXf8Hg9IMzUXJgk2SrUUVqXiETgK+XuzBPz+VnjH+lxb7WYoKJH9gqNoiWhA6ndSfyoOkdT34fjy96EkHRG5pjXJA=,iv:VBXc0AKU1j9qSZUtZO+9pBiIR+QVV2JnbYfWnT1xjGQ=,tag:utOnH0OS/F83ogW2paLZLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eUIrUE5xQkFkOFEveFVs
            eGJraEtLQ29mV2c0d3NsNHdNT0MrT0Q3Nm1RCjdSSmpXWU1SVVN1bG9aUFVvN0Zv
            VHhCRFVEd25aWDR0WWh1UVdwWC81SncKLS0tIG50L0lZeGpJNWxLY1I2bnFkR3VV
            dzFNZ2U5eFphS3VqR0FyMGpTTmVWajAKBoQClgeQ8nY2rmkq7JdJ47+ri7qKlnZi
            rNv7vinI7vxmAW7vcysb2WlOeW6c7gCZMHIFitkdSJo6Bd535JQdHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T13:49:52Z"
    mac: ENC[AES256_GCM,data:OxNqZGL42G4BAAKdinkZA0gbkaeWougwmZg2QQ3bFSV6gKpqI5HSYd61avxVMF8nah1B98ENfCQFVNj1Ul/ZJPRelEMjWwMztTA/L7GeIcyn/DmJPe82Zg1/Y3p8Cv8bLdzyF1j2kFnLsMUmHsEtCC1AL7oOY3NpBcwQDHGBsH4=,iv:8+XRfxdXBS1jmHuWGmWlLwzor1MvGu6/vdTAbh9sBCI=,tag:Vu/LEppvU8rn3Lib6tgfkw==,type:str]
    version: 3.13.2
