apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:HgWcDXLMs568y7ZBcd+zwccCHq8LQX6VRhO+aGBQ8lcdd8qNXl2Ssh219+QJlkmwqO1r76kpFCOj4T5/FnErTTdS74ATlCz8q2wwBfQhdXFMDhbUE5f4ICYAlSg7twO4uWwHkqmmw6Fprg7x57yk1hgyhylJQ46OqEgKBxiqZts6QNqyGjXGJA+cY1IVtqIglplHQqq9yl5ZyrxCnd+kJXsxqdzNSi/qm63t00oXsMdN6ZBXDdsK6AjtYtUyzeiztLOcUqlCunBPjbyPY1r+2YrY8fS1OXdhmc9HNUftRx/8fru9LrPBurNHbpJ1YCoDhGiSebvIlUKRPR7+faOHlhgSuQA=,iv:uoSDUW69cXzElCktQufyb4sTTckuLjnpId0MrvSp7PQ=,tag:sHMpmh99vYMwKnFh6nYH7w==,type:str]
kind: Secret
metadata:
    name: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L2o5QTZaV2JzNGxuc004
            SzB1ZjREbHNRL1phMnBGOE9PeTMrMVNJeDFBClpxSlVnWGdMSEpNcDNtc2V0ckJK
            cmdwSEgwckxibHhKdE15VTNES0dhQ00KLS0tIElXdEwzSHRTQTErbzdWRGNLU0RG
            bE03N1ZIMit5elNpcGJTLzROSHJJRlkKGZ1dseCQliU8d3ndDToSomWxGvWQVuve
            8A9eRj0OyIbHXBSUyC4WAZT0j/HlamLVMIKCMXFxoChneBTPymrHzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T19:35:46Z"
    mac: ENC[AES256_GCM,data:K8TtdexnJ6FqCW7lOWGEgHOFgr8QluWEy9vtdNPrre7TupYfZ3jkxeLZGazs/n/rV5N+WHU0LVpCqKQ1NOUNbqm2XuhY0q25r/lKxmCgjLt3z5cleztVr+DPgbDNI0kyqYFmFkJqL1j608HNa1wfmVnN/GscBKtqv7BKjDJQNP8=,iv:wMZJn3fD7EefoXWSDgcC+Y5PcPIxvGEk3/N3LHmadVk=,tag:XbCwqdg8FVJTZHoUTRne2g==,type:str]
    version: 3.13.1
