apiVersion: v1
kind: Secret
metadata:
    name: secret-backup
    namespace: forgejo-prod
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Ko3KeR9FhCPZUJqTGdN5ks2CHlf5NujL9Q==,iv:ED2x2VGL734VsNZxHAjLM20s57kTRlBAva3wRioFTGA=,tag:XLNxxfY2RsW6Zj/UVW+MjA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:z2jywWGsSk9j6wIQZ3TVR+eUJOmMa6j+NvHsUW+XJA==,iv:84aLSyREZNcP3BdzAhkv+xVSysxAZc9stSQl1tBTC1k=,tag:scx8I3v2eJsxqN6Pl0V11A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNWV5MEQxY054M0s4dnRn
            LzRDVnNJelRQU25pNDJXWUFBQ3ozNE9vRlJvCm1kZTRscDVwVHJId0RvVjU0MGtW
            V2l1a2VJWUxNb1ZVYUpuWXFKeFlPd2MKLS0tIC9YMGIrWHJCdkxRYjh4cWVjdmpz
            SW8yVnVPQkQrUFFuNWZpZURKUC9ELzAKTRYZMNQSy/1j5A5YGdz92Moe6gnvxNxZ
            N+ntZQ763nP+GLisQy8oWeWln8IMoSCBJNNo8K/bagBfJQC1fvtTIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5e046zzyrz29t2elgtmepqksjzlemra50kz334f5z695uwandus2v9cev
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T20:27:26Z"
    mac: ENC[AES256_GCM,data:iK5Xz/p175iYr0mR4Ojqr2dan8dhznUoI1SnDROpJ2Bd5MkcxXvx6skdKq/4i9gLKTDs/nKYDAZM5MDXmhG0R6mJHqGsghwriU5O8Ic+1GOkf4eaqJ0HPbjEDef6xNrLhYPmfITblIN3sSggP7Ruk/AilweWltq/8csMVqpYAog=,iv:rDISTm9RdDPqjdKfOD+Yw4XYJRxUd0eZOFGe/XBZN7Y=,tag:uIlczFYY01IcjLjQGVb0xQ==,type:str]
    version: 3.13.1
